const fs=require("fs");
const contain="THE INFORMATION SYSTEM IS SET OF INTER RELATED COMPONENT THAT COLLECT,MAINUPLATE AND PUBLISH DATA AND INFORMATION AND PROVIDE FEEDBACK MEET AN OBJECTIVE...!!! ";
fs.writeFile("write.txt",contain,"utf8",()=>{});
